--PART 8 QUERIES
--Write SQL queries based on your data warehouse to display the following information.
--Note: The values used to create these examples will not match current values in the database tables. 

-- Q1. LIST EACH WEEKDAY AND THE TOTAL SALES (QTY * SALEPRICE) IN DESC TOTAL SEQ


SELECT DD.DayName AS [WEEKDAY], SUM((DS.QTY) * DS.SALEPRICE) AS [TOTAL SALES]
FROM DWSALE DS
LEFT JOIN DWDATE DD
ON DS.SALE_DWDATEID = DD.DATEKEY
WHERE DD.DayName IS NOT NULL
GROUP BY DD.DayName
ORDER BY [TOTAL SALES] DESC;


-- Q2. List each cutomer catergory and the toal sales(qty * saleprice) in ASC total SEQ

SELECT DC.CUSTCATNAME AS [CUSTOMER CATEGORY], SUM((DS.QTY) * DS.SALEPRICE) AS [TOTAL SALES]
FROM DWSALE DS
LEFT JOIN DWCUST DC
ON DS.DWCUSTID = DC.DWCUSTID
WHERE DC.CUSTCATNAME IS NOT NULL
GROUP BY DC.CUSTCATNAME
ORDER BY [TOTAL SALES] ASC;


----CHECKING
--SELECT CC.CUSTCATNAME AS [CUSTOMER CATEGORY]
--FROM DWSALE DS
--inner JOIN TPS.DBO.CUSTCATEGORY CC
--ON DS.DWCUSTID = CC.Custcatcode


--Q3 List each product manufacturere and the total qty sold , list in DESC total seq

SELECT DP.PRODMANUNAME AS [PRODUCT MANUFACTURER], SUM(DS.QTY) AS [TOTAL QTY SOLD]
FROM DWSALE DS
LEFT JOIN DWPROD DP
ON DS.DWPRODID = DP.DWPRODID
WHERE DP.PRODMANUNAME IS NOT NULL
GROUP BY DP.PRODMANUNAME
ORDER BY [TOTAL QTY SOLD] DESC;

--Q4 List the top 10 custimers based on tial sales (qty * saleprie
--the list must be in descending total sequence)


SELECT TOP 10 DC.DWCUSTID AS [CUSTOMER ID], DC.FIRSTNAME, DC.SURNAME,  SUM((DS.QTY) * DS.SALEPRICE) AS [TOTAL SALES]
FROM DWSALE DS
LEFT JOIN DWCUST DC
ON DS.DWCUSTID = DC.DWCUSTID
WHERE DC.CUSTCATNAME IS NOT NULL
GROUP BY DC.DWCUSTID, DC.FIRSTNAME, DC.SURNAME
ORDER BY [TOTAL SALES] DESC;


--Q5 List the bottom 10 products based on total qty sales the list in ASC total SEQ

SELECT TOP 10 DP.DWPRODID AS [PRODUCT ID ], DP.PRODNAME, SUM(DS.QTY) AS [TOTAL QTY SALES]
FROM DWSALE DS
LEFT JOIN DWPROD DP
ON DS.DWCUSTID = DP.DWPRODID
WHERE DP.PRODNAME IS NOT NULL
GROUP BY DP.DWPRODID, DP.PRODNAME
ORDER BY [TOTAL QTY SALES] ASC;

--Q6. List the top city names based on total sales (qty * price) 
--for each ststate the list must be in ASC state SEQ

SELECT TOP 10 DC.[STATE] AS [STATE], DC.CITY, SUM((DS.QTY) * DS.SALEPRICE) AS [TOTAL SALES]
FROM DWSALE DS
LEFT JOIN DWCUST DC
ON DS.DWCUSTID = DC.DWCUSTID
WHERE DC.STATE IS NOT NULL
AND DC.CITY IS NOT NULL
GROUP BY DC.[STATE], DC.CITY
ORDER BY [STATE] ASC, [TOTAL SALES] DESC;


